# Generated by Django 3.1.1 on 2020-09-13 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200913_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
